version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: php
    restart: always
    volumes:
      - ./app:/var/www/html
    networks:
      - app_network
    depends_on:
      - mysql
    command: sh -c "php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && mv composer.phar /usr/local/bin/composer"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes_from:
      - php
    volumes:
      - ./app:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - app_network
    depends_on:
      - php

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: example
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  php:
