version: '3.8'

services:
  php:
    build: 
      context: php
      dockerfile: Dockerfile
    container_name: php
    restart: always
    volumes:
      - ./app:/var/www/html
    networks:
      - app_network
    depends_on:
      - mysql
    
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./html/:/usr/share/nginx/html/temp/
      - certs:/etc/letsencrypt
    networks:
      - app_network
    depends_on:
      - php
    environment:
      #-PRODHOSTNAME: domain.local
      #-DEVHOSTNAME: test.domain.local

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      # ------- CHANGE CREDENTIALS -------
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      # ------- CHANGE CREDENTIALS -------
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: example
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  certs:
